'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SAMU_Centre_15.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _17() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _18() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property actualité_accès_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actualité accès gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property afficher_le_dossier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("afficher le dossier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property alcatel_lucent_ringing() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("alcatel_lucent_ringing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alerte_d_Urgence_2020_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alerte d'Urgence 2020 blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alerte_d_Urgence_2020_blanc_couleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alerte d'Urgence 2020 blanc couleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aucunPluginSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aucunPluginSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bordure_titre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bordure titre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property débuter_service_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("débuter service gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property débuter_service_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("débuter service jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property détails_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("détails jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property détails_noir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("détails noir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property doc_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doc jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property doc_noir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doc noir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eclipse_1s_32px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eclipse-1s-32px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property étoilePleine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("étoilePleine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property étoileVide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("étoileVide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property fixe4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fixe4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fondlibre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondlibre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property haut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("haut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jouer_mode_libre_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jouer mode libre gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jouer_mode_libre_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jouer mode libre jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lancer_service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lancer service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property liste_plugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste plugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property liste_plugin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liste plugin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading-bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_08_09_2019() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo 08-09-2019", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_50__trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo 50 -trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_caré_vide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo caré vide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property microphone24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microphone24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mods_installés_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mods installés gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mods_installés_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mods installés jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mon_opérateur_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mon opérateur gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mon_opérateur_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mon opérateur jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property msgModManquants() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msgModManquants", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plugin_favori_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plugin favori gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property police_secours() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("police_secours", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property racrocher24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("racrocher24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property réglages_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("réglages gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property réglages_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("réglages jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property retour() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retour", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property samu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("samu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sapeurs_pompiers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sapeurs-pompiers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sms24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sms24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property statistiques_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statistiques gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property statistiques_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statistiques jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property succès_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("succès gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property succès_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("succès jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property suivi_des_appels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suivi des appels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property suivi_des_missions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suivi des missions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property suivi_des_moyens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suivi des moyens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property titre_zone_jaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titre zone jaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property tonalité() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("tonalité", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property uifx() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("uifx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property uiMsg() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("uiMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property uiWin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("uiWin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_2020_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager 2020 blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_2020_blanc_couleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager 2020 blanc couleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_2020_blanc_couleur1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager 2020 blanc couleur1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_2020_noir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager 2020 noir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_2020_noir_couleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager 2020 noir couleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_couleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager couleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Urgence_Manager_noir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Urgence Manager noir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ut_engune_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ut engune blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property utnetwork_blanc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("utnetwork blanc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property utnetwork_gris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("utnetwork gris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
